"""empty message

Revision ID: 68cf34fbd494
Revises: 
Create Date: 2020-05-20 13:17:10.564822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68cf34fbd494'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('volume', sa.String(length=10), nullable=False),
    sa.Column('volume_unit', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_id'), 'sample', ['id'], unique=False)
    op.create_index(op.f('ix_sample_name'), 'sample', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sample_name'), table_name='sample')
    op.drop_index(op.f('ix_sample_id'), table_name='sample')
    op.drop_table('sample')
    # ### end Alembic commands ###
